---
apiVersion: eda.ansible.com/v1alpha1
kind: EDA
metadata:
  name: automationeda
  namespace: ansible-automation-platform
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app.kubernetes.io/managed-by: eda-operator
    app.kubernetes.io/name: automationeda
    app.kubernetes.io/part-of: automationeda
    app.kubernetes.io/operator-version: ''
    argocd.argoproj.io/managed-by: openshift-gitops
spec:
  route_tls_termination_mechanism: Edge
  ingress_type: Route
  loadbalancer_port: 80
  no_log: true
  activation_worker:
    replicas: 5
  image_pull_policy: IfNotPresent
# Check IPV6
  ipv6_disabled: false
  ui:
    replicas: 1
  set_self_labels: true
  api:
    gunicorn_workers: 2
    replicas: 1
  force_drop_db: false
  scheduler:
    replicas: 1
  redis:
    replicas: 1
  automation_server_url: ''
  admin_user: admin
  loadbalancer_protocol: http
  default_worker:
    replicas: 2
  worker:
    replicas: 2
...
