---
apiVersion: v1
kind: Namespace
metadata:
  name: ansible-automation-platform
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    openshift.io/cluster-monitoring: "true"
    argocd.argoproj.io/managed-by: openshift-gitops
...
