---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

labels:
- includeSelectors: true
  pairs:
    env: dev

namespace: aap-dev
namePrefix: dev-

patches:
- path: operator-group-patch.yaml
  target:
    group: operators.coreos.com
    kind: OperatorGroup
    name: ansible-automation-platform-operator
- path: subscription-patch.yaml
  target:
    group: operators.coreos.com
    kind: Subscription
    name: ansible-automation-platform
- path: automatinhub-patch.yaml
  target:
    group: automationhub.ansible.com
    kind: AutomationHub
    name: automationhub
- path: consolelink-patch.yaml
  target:
    group: console.openshift.io
    kind: ConsoleLink
    name: controllerlink
...
